### ISSUE TITLE
contact request for cmurphy

### ISSUE THREAD

**Issue by craftycram** [bikeshare-capstone-pdx/bikeshare-web#48]
Hey Colleen,
I wasn't sure how to contact you the best so I'm just using this repository here, cause I saw that you're the only member in this organization.
My team and I created a service at university that we want to release soon and we figured that an organization on GitHub to keep our code in one organized place would be the best way to go.
Since our service is called "bikeshare" we figured to name the organization that way for the students to easily find it, but we saw that you already created one called that way.
Since there wasn't any activity in here the last few years I thought that imma just ask you if it would be fine for you renaming the organization slightly allowing us to use "bikeshare" as the name of ours.
Kind regards,
Marc

**Comment by cmurphy** [comment]
Hi Marc, thanks for reaching out and sorry I didn't see this right away. This was just a university class project so we don't mind giving up the name. I've gone ahead and renamed this org. Best of luck with your bikeshare project :smile:

**Comment by craftycram** [comment]
awesome! thanks for the reply and for renaming the org. have a nice weekend!
